language: go

go:
  - 1.13.x

git:
  depth: 1

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $HOME/.local
    - $HOME/.kube

before_install: skip

install:
  # install kube builder so BDD test cases can work
  - make kubebuilder

jobs:
  include:

    - stage: unit-test
      if: type IN (push, pull_request)
      script:
        - make test
        - bash <(curl -s https://codecov.io/bash)
        - make docker-build

    - stage: publish-image
      if: type IN (push)
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # this should overwrite "latest" image with the latest version one
        - make docker-build
        - make docker-push
        - if [ $TRAVIS_EVENT_TYPE = push ]; then export IMG=keikoproj/iam-manager:$TRAVIS_BRANCH; fi
        - make docker-build
        - make docker-push